pip3 install -t . httplib2 --upgrade

curl "$GOOGLE_CHAT_WEBHOOK_SERVICES_REPO/bitrise/step-code.py" | python3 - \
"$GOOGLE_CHAT_WEBHOOK_URL" \
"$JIRA_ORGANIZATION_NAME" \
"$JIRA_TEAM_NAME" \
"$BITRISE_APP_TITLE" \
"$BITRISE_BUILD_STATUS" \
"$BITRISE_BUILD_NUMBER" \
"$BITRISE_TRIGGERED_WORKFLOW_TITLE" \
"$BITRISE_BUILD_URL" \
"$BITRISE_PUBLIC_INSTALL_PAGE_URL" \
"$BITRISE_GIT_BRANCH" \
"$BITRISE_GIT_MESSAGE" \
"$BITRISE_PULL_REQUEST" \
"$BITRISEIO_GIT_BRANCH_DEST" \
"$BITRISEIO_PULL_REQUEST_REPOSITORY_URL" \
"$TEAM_DEVELOPER_USERIDS" \
"$TEAM_TESTER_USERIDS"
