GOOGLE_CHAT_WEBHOOK_URL='https://chat.googleapis.com/v1/spaces/AAAAhHdpKEc/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=RKLEEqXK4WJWW-Eqa_eyunlMARCopm5LPiUdagxKOxs%3D'
GOOGLE_CHAT_WEBHOOK_SERVICES_REPO='https://bitbucket.org/ascend-kyu/google-chat-webhook-services/raw/develop'

JIRA_ORGANIZATION_NAME='ORGANIZATION_NAME'
JIRA_TEAM_NAME='TEAM_NAME'

TEAM_DEVELOPER_USERIDS='106771966467879575916'
TEAM_TESTER_USERIDS='106771966467879575916'

BITRISE_APP_TITLE='PROJECT_NAME'
BITRISE_BUILD_STATUS='0'
BITRISE_BUILD_NUMBER='1'
BITRISE_TRIGGERED_WORKFLOW_TITLE='WORKFLOW_NAME'
BITRISE_BUILD_URL='https://www.google.com'
BITRISE_PUBLIC_INSTALL_PAGE_URL='https://www.google.com'
BITRISE_GIT_BRANCH='BRANCH_NAME'
BITRISE_GIT_MESSAGE="GIT COMMIT MESSAGE

[TEAM_NAME-0001] JIRA Task A
[TEAM_NAME-0002] JIRA Task B
"
BITRISE_PULL_REQUEST='1'
BITRISEIO_PULL_REQUEST_REPOSITORY_URL='git@bitbucket.org:project_owner/project_name.git'
BITRISEIO_GIT_BRANCH_DEST='DESTINATION_BRANCH_NAME'

BUILD_NOTE='BUILD_NOTE'

GOOGLE_CHAT_CONFIGURATIONS='isGitMessageEnabled'